name: On Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  test:
    uses: "./.github/workflows/job-test.yml"
    with:
      with-coverage: true
